version: '3.1'
volumes:
  vault_data:
services:
  vault:
    image: hashicorp/vault:latest
    logging:
      driver: none
    restart: always
    container_name: vault
    dns:
      - 10.4.4.34
      - 1.4.4.100
      - 1.1.1.1
    ports:
      - 8200:8200
    networks:
      - vault_net
    volumes:
      - "/docker/vault/logs:/vault/logs"
      - "/docker/vault/file:/vault/file"
      - "/docker/vault/config:/vault/config"
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
networks:
  vault_net: