version: '3.1'

services:
  joomla:
    image: joomla:1.0
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
      - 8443:443
    networks:
      - joomla_net
    volumes:
      - "../:/var/www/html"
      - "/docker/ssl:/etc/ssl"
      - "/docker/apache2/sites-enabled:/etc/apache2/sites-enabled"
      - "/docker/apache2/sites-available:/etc/apache2/sites-available"
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: SECRET

  joomladb:
    image: mysql:5.6
    ports:
      - 3306
    networks:
      - joomla_net
    restart: always
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: SECRET

networks:
  joomla_net: